function [fitresult, gof] = createFit(fittingX, fittingY)
%CREATEFIT1(FITTINGX,FITTINGY)
%  Create a fit.
%
%  Data for 'N2 -> N2(A3,v0-4)' fit:
%      X Input: fittingX
%      Y Output: fittingY
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 05-Nov-2024 11:47:18


%% Fit: 'N2 -> N2(A3,v0-4)'.
[xData, yData] = prepareCurveData( fittingX, fittingY );

% Set up fittype and options.
ft = fittype( 'smoothingspline' );
opts = fitoptions( 'Method', 'SmoothingSpline' );
opts.SmoothingParam = 1;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% % Plot fit with data.
% figure( 'Name', 'N2 -> N2(A3,v0-4)' );
% h = plot( fitresult, xData, yData );
% legend( h, 'fittingY vs. fittingX', 'N2 -> N2(A3,v0-4)', 'Location', 'NorthEast', 'Interpreter', 'none' );
% % Label axes
% xlabel( 'fittingX', 'Interpreter', 'none' );
% ylabel( 'fittingY', 'Interpreter', 'none' );
% grid on


