function fsFilamentSpectraExposure2nsDelay0s = importSpectra(filename, dataLines)
%IMPORTFILE Import data from a text file
%  FSFILAMENTSPECTRAEXPOSURE2NSDELAY0S = IMPORTFILE(FILENAME) reads data
%  from text file FILENAME for the default selection.  Returns the data
%  as a table.
%
%  FSFILAMENTSPECTRAEXPOSURE2NSDELAY0S = IMPORTFILE(FILE, DATALINES)
%  reads data for the specified row interval(s) of text file FILENAME.
%  Specify DATALINES as a positive scalar integer or a N-by-2 array of
%  positive scalar integers for dis-contiguous row intervals.
%
%  Example:
%  fsFilamentSpectraExposure2nsDelay0s = importfile("/Users/sethwilson/Library/CloudStorage/OneDrive-Colostate/fs-ns Dual Pulse/Seth's Local Files/ZDPlasKin/BOLSIG Rates/Isolate Reactions/380nm/fs-Filament Spectra, Exposure 2 ns, Delay 0s.dat", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 25-Nov-2024 19:11:34

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 3);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = " ";

% Specify column names and types
opts.VariableNames = ["e02", "e00", "VarName3"];
opts.VariableTypes = ["double", "double", "double"];

% Specify file level properties
opts.ImportErrorRule = "omitvar";
opts.MissingRule = "omitvar";
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";
opts.LeadingDelimitersRule = "ignore";

% Specify variable properties
opts = setvaropts(opts, "e02", "TrimNonNumeric", true);
opts = setvaropts(opts, "e02", "ThousandsSeparator", ",");

% Import the data
fsFilamentSpectraExposure2nsDelay0s = readtable(filename, opts);

% Set variable Names
fsFilamentSpectraExposure2nsDelay0s.Properties.VariableNames(1) = {'Wavelength [nm]'};
fsFilamentSpectraExposure2nsDelay0s.Properties.VariableNames(2) = {'Intensity [au]'};
end